server.port=8088
spring.application.name=sobrancelhas

# Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:ateliedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o painel visual do H2 para você ver os dados inseridos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria as tabelas automaticamente com base nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
